
package com.vg.gomoku.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://gomoku.vg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @return
     *     returns com.vg.gomoku.webservice.Model
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCurrentModel", targetNamespace = "http://gomoku.vg.com/", className = "com.vg.gomoku.webservice.GetCurrentModel")
    @ResponseWrapper(localName = "getCurrentModelResponse", targetNamespace = "http://gomoku.vg.com/", className = "com.vg.gomoku.webservice.GetCurrentModelResponse")
    @Action(input = "http://gomoku.vg.com/Server/getCurrentModelRequest", output = "http://gomoku.vg.com/Server/getCurrentModelResponse")
    public Model getCurrentModel();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "makeMove", targetNamespace = "http://gomoku.vg.com/", className = "com.vg.gomoku.webservice.MakeMove")
    @ResponseWrapper(localName = "makeMoveResponse", targetNamespace = "http://gomoku.vg.com/", className = "com.vg.gomoku.webservice.MakeMoveResponse")
    @Action(input = "http://gomoku.vg.com/Server/makeMoveRequest", output = "http://gomoku.vg.com/Server/makeMoveResponse")
    public void makeMove(
        @WebParam(name = "arg0", targetNamespace = "")
        ClientAction arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "connectAndGetPlayerNumber", targetNamespace = "http://gomoku.vg.com/", className = "com.vg.gomoku.webservice.ConnectAndGetPlayerNumber")
    @ResponseWrapper(localName = "connectAndGetPlayerNumberResponse", targetNamespace = "http://gomoku.vg.com/", className = "com.vg.gomoku.webservice.ConnectAndGetPlayerNumberResponse")
    @Action(input = "http://gomoku.vg.com/Server/connectAndGetPlayerNumberRequest", output = "http://gomoku.vg.com/Server/connectAndGetPlayerNumberResponse")
    public int connectAndGetPlayerNumber();

}
